databases:
  - name: financedb
    plan: free

services:
  - type: web
    plan: free
    name: personalWeb
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn personalWeb.asgi:application -k uvicorn.Workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:fairygodmother@localhost:543i1/postgres
        fromDatabase:
          name: financedb
          property: connectionString
      - key: SECRET_KEY
        generatrValue: true
      - key: WEB_CONCURRENcy
        value: 4

