databases:
  - name: financedb
    plan: free
    databaseName: DATABASE_NAME
    user: DATABASE_USERNAME
services:
  - type: web
    plan: free
    name: finance
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn personalWeb.asgi:application -k uvicorn.Workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

