# Generated by Django 5.1.5 on 2025-07-22 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_description', models.TextField()),
                ('i_price', models.FloatField(default=0.0)),
                ('i_total_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('b_balance', models.FloatField(default=0.0)),
                ('b_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(blank=True, max_length=20, null=True)),
                ('u_address', models.CharField(blank=True, max_length=200, null=True)),
                ('u_phone', models.CharField(blank=True, default=0, null=True)),
                ('u_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_amount', models.FloatField(default=0.0)),
                ('t_type', models.CharField(max_length=13)),
                ('t_creation', models.DateTimeField(auto_now=True)),
                ('t_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.bankinfo')),
                ('t_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.userinfo')),
            ],
        ),
    ]
