# Generated by Django 5.1.5 on 2025-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='u_avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
