# Generated by Django 5.1.5 on 2025-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_transactions_t_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='t_type',
            field=models.CharField(max_length=13),
        ),
    ]
