<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_transactions_t_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_description', models.TextField()),
                ('i_price', models.FloatField(default=0.0)),
                ('i_total_quantity', models.IntegerField()),
            ],
        ),
    ]
=======
# Generated by Django 5.1.5 on 2025-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_transactions_t_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_description', models.TextField()),
                ('i_price', models.FloatField(default=0.0)),
                ('i_total_quantity', models.IntegerField()),
            ],
        ),
    ]
>>>>>>> 97e92ee8075d69ff70ccadfb195608c94e134cf8
